-- ======================================
-- CLEANUP - HAPUS SEMUA TABEL & TYPE
-- JALANKAN INI DULU SEBELUM SEED
-- ======================================

-- Matikan RLS jika aktif
DO $$ BEGIN
  ALTER TABLE "AuditLog" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "WasteItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Waste" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "BarangKeluarItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "BarangKeluar" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "BarangMasukItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "BarangMasuk" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "OpnameItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Opname" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "StokBatch" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Stok" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Verifikasi" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "PembelianItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Pembelian" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "MenuPlanItem" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "MenuPlan" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "ResepBahan" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Resep" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Barang" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "Satuan" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "KategoriBarang" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN null;
END $$;

-- Drop FK constraints
DO $$ BEGIN ALTER TABLE "AuditLog" DROP CONSTRAINT IF EXISTS "AuditLog_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "WasteItem" DROP CONSTRAINT IF EXISTS "WasteItem_wasteId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "WasteItem" DROP CONSTRAINT IF EXISTS "WasteItem_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Waste" DROP CONSTRAINT IF EXISTS "Waste_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangKeluarItem" DROP CONSTRAINT IF EXISTS "BarangKeluarItem_barangKeluarId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangKeluarItem" DROP CONSTRAINT IF EXISTS "BarangKeluarItem_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangKeluar" DROP CONSTRAINT IF EXISTS "BarangKeluar_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangMasukItem" DROP CONSTRAINT IF EXISTS "BarangMasukItem_barangMasukId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangMasukItem" DROP CONSTRAINT IF EXISTS "BarangMasukItem_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangMasuk" DROP CONSTRAINT IF EXISTS "BarangMasuk_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "BarangMasuk" DROP CONSTRAINT IF EXISTS "BarangMasuk_pembelianId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "OpnameItem" DROP CONSTRAINT IF EXISTS "OpnameItem_opnameId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "OpnameItem" DROP CONSTRAINT IF EXISTS "OpnameItem_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Opname" DROP CONSTRAINT IF EXISTS "Opname_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "StokBatch" DROP CONSTRAINT IF EXISTS "StokBatch_stokId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Stok" DROP CONSTRAINT IF EXISTS "Stok_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Verifikasi" DROP CONSTRAINT IF EXISTS "Verifikasi_pembelianId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Verifikasi" DROP CONSTRAINT IF EXISTS "Verifikasi_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "PembelianItem" DROP CONSTRAINT IF EXISTS "PembelianItem_pembelianId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "PembelianItem" DROP CONSTRAINT IF EXISTS "PembelianItem_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Pembelian" DROP CONSTRAINT IF EXISTS "Pembelian_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "MenuPlanItem" DROP CONSTRAINT IF EXISTS "MenuPlanItem_menuPlanId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "MenuPlanItem" DROP CONSTRAINT IF EXISTS "MenuPlanItem_resepId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "MenuPlan" DROP CONSTRAINT IF EXISTS "MenuPlan_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "ResepBahan" DROP CONSTRAINT IF EXISTS "ResepBahan_resepId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "ResepBahan" DROP CONSTRAINT IF EXISTS "ResepBahan_barangId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Resep" DROP CONSTRAINT IF EXISTS "Resep_userId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Barang" DROP CONSTRAINT IF EXISTS "Barang_kategoriId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;
DO $$ BEGIN ALTER TABLE "Barang" DROP CONSTRAINT IF EXISTS "Barang_satuanId_fkey"; EXCEPTION WHEN OTHERS THEN null; END $$;

-- Drop all tables
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "WasteItem" CASCADE;
DROP TABLE IF EXISTS "Waste" CASCADE;
DROP TABLE IF EXISTS "BarangKeluarItem" CASCADE;
DROP TABLE IF EXISTS "BarangKeluar" CASCADE;
DROP TABLE IF EXISTS "BarangMasukItem" CASCADE;
DROP TABLE IF EXISTS "BarangMasuk" CASCADE;
DROP TABLE IF EXISTS "OpnameItem" CASCADE;
DROP TABLE IF EXISTS "Opname" CASCADE;
DROP TABLE IF EXISTS "StokBatch" CASCADE;
DROP TABLE IF EXISTS "Stok" CASCADE;
DROP TABLE IF EXISTS "Verifikasi" CASCADE;
DROP TABLE IF EXISTS "PembelianItem" CASCADE;
DROP TABLE IF EXISTS "Pembelian" CASCADE;
DROP TABLE IF EXISTS "MenuPlanItem" CASCADE;
DROP TABLE IF EXISTS "MenuPlan" CASCADE;
DROP TABLE IF EXISTS "ResepBahan" CASCADE;
DROP TABLE IF EXISTS "Resep" CASCADE;
DROP TABLE IF EXISTS "Barang" CASCADE;
DROP TABLE IF EXISTS "Satuan" CASCADE;
DROP TABLE IF EXISTS "KategoriBarang" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- Drop custom enums
DROP TYPE IF EXISTS "Role" CASCADE;
DROP TYPE IF EXISTS "TipePembelian" CASCADE;
DROP TYPE IF EXISTS "StatusPembelian" CASCADE;
DROP TYPE IF EXISTS "StatusVerifikasi" CASCADE;
